
server:
  servlet:
    context-path: /api

spring:
  application:
    name: jolly-api

  main:
    banner-mode: off

  datasource:
    username: user
    password: secret
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        transaction:
          coordinator_class: jdbc
    open-in-view: false

security:
  jwt:
    secret-key: secret2